version: '3.9'

services:
  backend:
    env_file: ./env
    build:
      context: backend
      target: production

  frontend:
    env_file: ./env
    build:
      context: frontend

  database:
    env_file: ./env
    image: postgres:13
    volumes:
      - ./database/data:/var/lib/postgresql/data
