version: '3.9'

services:
  backend:
    env_file: ./env
    build:
      context: backend
      target: production
    depends_on:
      - "database"

  frontend:
    env_file: ./env
    build:
      context: frontend
    depends_on:
      - "backend"

  database:
    env_file: ./env
    image: postgres:13
    volumes:
      - ./database/data:/var/lib/postgresql/data
