# Generated by Django 3.2 on 2021-05-31 15:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_auto_20210531_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 31, 15, 21, 57, 201940, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
