# Generated by Django 3.2 on 2021-05-31 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_auto_20210530_1553"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="type",
        ),
    ]
